feat: Add Users list api spec, update CHANGELOG and refactor dev server
supertokens/dashboard pull request #7
Opened 2022-07-20 08:10 UTC by nkshah2

- Adds the API spec for `/users GET`
- Adds steps to test in production mode to CONTRIBUTING
- Return error messages from the dev servers default error handler when returning status 500 to help with debugging

2022-07-20 12:15 UTC, rishabhpoddar requested changes

2022-07-20 12:15 UTC, rishabhpoddar commented on api_spec.yaml
> +                            - type: object
Also send user metadata object back for each user

2022-07-20 12:25 UTC, nkshah2 commented on api_spec.yaml
> +                        nextPaginationToken:
This should be outside the users array

2022-07-25 13:30 UTC, rishabhpoddar approved these changes

2022-07-25 13:30 UTC, merged